version: "3.9"

volumes:
  db:
  rabbitmq:

services:
  db:
    image: library/postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "${SWAGGER_PORT}:8080"
    environment:
      - API_URL=http://localhost:8888/swagger.json
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "${AMQP_PORT}:5672"
      - "${AMQP_UI_PORT}:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
