logger:
  level: debug # trace|debug|info|warn|error|fatal|panic

db:
  type: psql # psql|memory

  #required if type = psql
  psql:
    url: "postgres://postgres:password@localhost:5435/postgres" # Example: postgres://{user}:{password}@{hostname}:{port}/{database-name}

http:
  host: ""
  port: 8010

grpc:
  host: ""
  port: 8020